//cellular automata
//ugens and classes

//maintained in github 
https://github.com/yotamorimoto/ca4sc

//.zip package
http://yotamorimoto.github.com/ca4sc/

[CA1]	1d binary ca. 1 neighbour
[CA2]	1d binary ca. 2 neighbour
[CA1x]	cubic interpolation
[CA2x]	cubic interpolation

//pattern
[Pca1]
[Pca2]

//2d
?

//references
"hacking cellular automata: an approach to sound synthesis"

//contact
yota morimoto
yotamorimoto@gmail.com