//ca4sc: cellular automata for supercollider
//ugens and classes

//maintained in github
https://github.com/yotamorimoto/ca4sc


[CA1]	1d binary ca. 1 neighbour
[CA2]	1d binary ca. 2 neighbour
[CA1x]	cubic interpolation
[CA2x]	cubic interpolation

//pattern
[Pca1]
[Pca2]

//TODO
ugen change rule at kr?

//references
"hacking cellular automata: an approach to sound synthesis"

//contact
yota morimoto
yotamorimoto [at] gmail.com